/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import javax.swing.JOptionPane;
import sesion2508.Producto;

/**
 *
 * @author labc205
 */
public class FrmProducto extends javax.swing.JFrame {
    private static int max = 3;
    Producto productos[] = new Producto[10];
    int i = 0;
    

    /**
     * Creates new form FrmProducto
     */
    public FrmProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblid = new javax.swing.JLabel();
        jLblna = new javax.swing.JLabel();
        jLblpr = new javax.swing.JLabel();
        jLblex = new javax.swing.JLabel();
        jTfid = new javax.swing.JTextField();
        jTfna = new javax.swing.JTextField();
        jTfpr = new javax.swing.JTextField();
        jTfex = new javax.swing.JTextField();
        jBtncl = new javax.swing.JButton();
        jBtnsa = new javax.swing.JButton();
        jBtnsh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTaregi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Productos");

        jLblid.setText("ID:");

        jLblna.setText("Name:");

        jLblpr.setText("Price:");

        jLblex.setText("Existence:");

        jTfna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfnaActionPerformed(evt);
            }
        });

        jBtncl.setText("Clean");
        jBtncl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnclActionPerformed(evt);
            }
        });

        jBtnsa.setText("Save");
        jBtnsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnsaActionPerformed(evt);
            }
        });

        jBtnsh.setText("show");

        jTaregi.setColumns(20);
        jTaregi.setRows(5);
        jScrollPane1.setViewportView(jTaregi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblex)
                            .addComponent(jLblid)
                            .addComponent(jLblna)
                            .addComponent(jLblpr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTfex, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTfpr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTfna, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jBtncl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnsa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnsh)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblid)
                    .addComponent(jTfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblna)
                    .addComponent(jTfna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblpr)
                    .addComponent(jTfpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblex)
                    .addComponent(jTfex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtncl)
                    .addComponent(jBtnsa)
                    .addComponent(jBtnsh))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTfnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfnaActionPerformed

    private void jBtnclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnclActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_jBtnclActionPerformed
    
    private void Limpiar(){
        jTfid.setText("");
        jTfna.setText("");
        jTfpr.setText("");
        jTfex.setText("");
        jTfid.requestFocus();
    }
    
    private void jBtnsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnsaActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jTfid.getText());
        String name = jTfna.getText();
        double price = Double.parseDouble(jTfpr.getText());
        int existance = Integer.parseInt(jTfex.getText());
        if(i<max){
            Producto prod = new Producto(id, name, price, existance);
            productos[i]= prod;
            i++;
            JOptionPane.showMessageDialog(this, "Registro guardado", "Guardar", JOptionPane.INFORMATION_MESSAGE);
            mostrarRegistros();
            Limpiar();
        }else{
            JOptionPane.showMessageDialog(this, "No se puede agregar mas productos","Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBtnsaActionPerformed

    private void mostrarRegistros(){
        String reg ="";
        for (int cont = 0; cont < i; cont++){
            reg+=productos[cont].toString();
        }
        jTaregi.setText(reg);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtncl;
    private javax.swing.JButton jBtnsa;
    private javax.swing.JButton jBtnsh;
    private javax.swing.JLabel jLblex;
    private javax.swing.JLabel jLblid;
    private javax.swing.JLabel jLblna;
    private javax.swing.JLabel jLblpr;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTaregi;
    private javax.swing.JTextField jTfex;
    private javax.swing.JTextField jTfid;
    private javax.swing.JTextField jTfna;
    private javax.swing.JTextField jTfpr;
    // End of variables declaration//GEN-END:variables
}
